// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8ecIAaw3SxaL8eeYPh_nqZZrH1w_ROio',
    appId: '1:811759084083:web:994b281093348827cbb946',
    messagingSenderId: '811759084083',
    projectId: 'fundio-76780',
    authDomain: 'fundio-76780.firebaseapp.com',
    storageBucket: 'fundio-76780.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWk2kf8ufv1xjA1SE-IrbMv_kY9n6d-mo',
    appId: '1:811759084083:android:8c216d7222392c68cbb946',
    messagingSenderId: '811759084083',
    projectId: 'fundio-76780',
    storageBucket: 'fundio-76780.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1RYV-mwPaBQn7mFWNMwrdM0RoL3l1df8',
    appId: '1:811759084083:ios:f1f4f13e3e25555fcbb946',
    messagingSenderId: '811759084083',
    projectId: 'fundio-76780',
    storageBucket: 'fundio-76780.firebasestorage.app',
    iosClientId: '811759084083-t7vn59be2kcaf1k1uvic73pdq7l65c6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.fundio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1RYV-mwPaBQn7mFWNMwrdM0RoL3l1df8',
    appId: '1:811759084083:ios:f1f4f13e3e25555fcbb946',
    messagingSenderId: '811759084083',
    projectId: 'fundio-76780',
    storageBucket: 'fundio-76780.firebasestorage.app',
    iosClientId: '811759084083-t7vn59be2kcaf1k1uvic73pdq7l65c6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.fundio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8ecIAaw3SxaL8eeYPh_nqZZrH1w_ROio',
    appId: '1:811759084083:web:8fa512cf3a93397fcbb946',
    messagingSenderId: '811759084083',
    projectId: 'fundio-76780',
    authDomain: 'fundio-76780.firebaseapp.com',
    storageBucket: 'fundio-76780.firebasestorage.app',
  );
}
